### ISSUE TITLE
CFG SAMS Detection

### ISSUE THREAD

**Issue by horizonramdisk** [horizonramdisk/Horizon-Ramdisk-ti994a#4]
Awareness only:  CFG assumes the SAMS memory card memory map is in its default powerup state.  If launched from a task that modifies the mapping, CFG may crash when it initiates the SAMS memory scan.  Decision point is whether to check the memory map prior to the execution or leave as-is.

**Comment by MirrorPusher** [comment]
I can confirm that I ran into this issue. I wondered why CFG didn't play along when loaded from TI Basic after running Stevie.
CFG indeed locks up during device scan. 
The root cause being that Stevie changes SAMS banks (and doesn't reset them to the default ones) upon exit.

Handling Stevie bugfix in a separate GitHub issue in Stevie repo.

**Comment by horizonramdisk** [comment]
Thanks for the confirmation.  I'll review the scan approach and see if there is a better way to handle the memory map at scan time.

**Comment by horizonramdisk** [comment]
Replaced SAMS detection with a non-destructive approach that doesn't rely upon any particular mapping register configuration.  Classic99 test was successful. Posted code on AtariAge for comment.

**Comment by horizonramdisk** [comment]
atrax tested with real hardware. Closing issue.
